[package]
name = "seshat-protocol"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true
keywords.workspace = true

[dependencies]
bytes = "1.5"
thiserror = "1.0"
